### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by tnguyenblurb** [smurfik/dropbox_api_v2#1]
I got the error below after installing this gem on Ruby 1.9.3. @bookis @smurfik Could you guys help me out?

/data/rbenv/.rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/bundler/gems/rails-43b134652d66/activesupport/lib/active_support/inflector.rb:3:in `<top (required)>': iconv will be deprecated in the future, use String#encode instead.
/data/rbenv/.rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/bundler/gems/rails-43b134652d66/activesupport/lib/active_support/dependencies.rb:182:in `require': /data/rbenv/.rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/gems/dropbox_api_v2-0.1.6/lib/dropbox_api_v2/request.rb:55: syntax error, unexpected ':', expecting tASSOC (SyntaxError)
...    headers = {"Authorization": "Bearer #{@token}", "Content...
...                               ^
/data/rbenv/.rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/gems/dropbox_api_v2-0.1.6/lib/dropbox_api_v2/request.rb:55: syntax error, unexpected ',', expecting keyword_end
...orization": "Bearer #{@token}", "Content-Type": content_type}
...                               ^
/data/rbenv/.rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/gems/dropbox_api_v2-0.1.6/lib/dropbox_api_v2/request.rb:55: syntax error, unexpected ':', expecting keyword_end
...rer #{@token}", "Content-Type": content_type}
...                               ^

**Comment by smurfik** [comment]
I'll look into it

**Comment by tnguyenblurb** [comment]
great! thanks @smurfik .

**Comment by smurfik** [comment]
ruby version 1.9.3 is not supported by the gem --  it works well with ruby version 2.3.0 and higher

I'll update the gemspec -- thanks for catching it!
